import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import math
from backend import simulate_retirement_planning


def main():
    st.set_page_config(initial_sidebar_state="expanded")

    st.title("Retirement Savings Simulation")

    st.sidebar.header("Adjust Parameters")

    # User inputs
    initial_age = st.sidebar.slider("Current Age", 20, 70, 30)
    retirement_age = st.sidebar.slider("Retirement Age", initial_age + 1, 80, 65)
    end_age = st.sidebar.slider("Age Until Funds Are Tracked", math.floor(retirement_age/5) * 5 + 5, 120, 90, step = 5)

    initial_savings = st.sidebar.number_input("Initial Savings", value = 20000.0, step = 1000.0)
    monthly_contribution = st.sidebar.number_input("Monthly Deposits Before Retirement", value = 500.0, step = 50.0)
    monthly_spending = st.sidebar.number_input("Monthly Payouts During Retirement", value = 2000.0, step = 100.0)
    annual_return = st.sidebar.slider("Expected Annual Return (%)", 0.0, 15.0, 5.0, step = 0.05)
    st.sidebar.caption("5% is a conservative estimate for a world index.")
    annual_inflation = st.sidebar.slider("Expected Annual Inflation (%)", -2.5, 10.0, 2.25, step = 0.125)
    adjust_for_inflation = st.sidebar.checkbox("Adjust Deposits For Inflation.", value = True)
    #st.sidebar.write("Explanation")
    st.sidebar.caption("Monthly deposits are then updated to match last year's inflation by the beginning of each year.")
    tax_rate = st.sidebar.slider("Expected Tax Rate On Payout (%).", 0.0, 75., 0.0, step = 2.5)

    df = simulate_retirement_planning(initial_age, 
                                    retirement_age, 
                                    end_age, 
                                    monthly_contribution, 
                                    monthly_spending, 
                                    annual_return, 
                                    initial_savings, 
                                    inflation_rate = annual_inflation,
                                    inflation_adjustment = adjust_for_inflation,
                                    tax_rate = tax_rate
                             )

    
    st.subheader("Projected Account Balance Over Time")
    #st.line_chart(df.set_index('Age')['Balance'])
    
    # Split data into positive and negative parts
    df_pos = df[df['Balance'] >= 0].copy()
    df_neg = df[df['Balance'] < 0].copy()

    # Create figure
    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x = df['Age'],
        y = df['Balance'],
        mode = 'lines',
        name = 'Balance',
        line = dict(color='rgba(51, 255, 255, 0.95)'),
        hovertemplate='Age: %{x}<br>Balance: %{y}<extra></extra>'
    ))

    # Add positive area
    if not df_pos.empty:
        fig.add_trace(go.Scatter(
            x = df_pos['Age'],
            y = df_pos['Balance'],
            fill = 'tozeroy',
            mode = 'none',
            name = 'Positive Balance',
            fillcolor = 'rgba(0, 128, 0, 0.3)'  # green 
        ))

    # Add negative area
    if not df_neg.empty:
        fig.add_trace(go.Scatter(
            x = df_neg['Age'],
            y = df_neg['Balance'],
            fill = 'tozeroy',
            mode = 'none',
            name = 'Negative Balance',
            fillcolor = 'rgba(255, 0, 0, 0.3)'  # red 
        ))

    # Update layout
    fig.update_layout(
        title = "Retirement Savings Projection (inflation adjusted)",
        xaxis_title = "Age",
        yaxis_title = "Balance",
        xaxis = dict(range = [initial_age, end_age], 
                    showgrid = True     
                    #gridcolor = 'lightgray'
                    ),
        yaxis=dict(showgrid = True     
                    #gridcolor = 'lightgray'
                    ),
        width = 700,
        height = 500,
        showlegend = False
    )

    # Display plot
    st.plotly_chart(fig, use_container_width = True)


    st.subheader("Detailed Balance Sheet (inflation ajusted)")
    st.dataframe(df.style.format({"Balance": "{:,.2f}"}))

    if df['Balance'].iloc[-1] < 0:
        st.error("You may run out of money before your desired end age.")
    else:
        st.success("Your funds are likely to suffice through your selected retirement span.")

    st.divider()

    st.subheader("Disclaimer")
    st.markdown("""The financial planning tool provided on this website/application is for *informational and educational purposes only*. It is a general tool designed to help users understand basic financial concepts and explore possible financial outcomes based on user-provided data. The projections and suggestions generated by this tool are **not intended** as, and do not constitute, *financial*, *investment*, *legal*, *tax*, or *other professional advice*.

While we strive to ensure the accuracy and reliability of the tool, we *make no guarantees or warranties*, express or implied, regarding the completeness, accuracy, timeliness, or results obtained from the use of this tool. Financial planning outcomes are inherently uncertain and can be influenced by a wide range of factors beyond our control, including market conditions, interest rates, inflation, and individual financial behavior.

**You are solely responsible for any decisions you make** based on the use of this tool. Before making any financial decisions, you should consult with a qualified financial advisor or other appropriate professional who is aware of your individual circumstances.

By using this tool, you acknowledge and agree that the creators, developers, and distributors of this tool **bear no responsibility or liability** for any losses, damages, or consequences of any kind arising from its use.
""")

    st.divider()
    
    if st.button("Clear Cache"):
        st.cache_data.clear()
        st.rerun()

if __name__ == "__main__":
    main()